language: node_js
node_js:
  - "node"
env:
  - CXX=g++-4.8
  - VERSION=0.7.20
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - "node_modules"